### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by elmarti** [VeliovGroup/Meteor-Files-Demos#1]
Hi, I was hoping to use this in a non-profit project, however my organisation requires clarity on the licensing. Can you confirm what license you follow for use of this demo, or any terms?

Thanks!

**Comment by dr-dimitru** [comment]
Hello @elmarti ,

Licence inherits from [parent-project](https://github.com/VeliovGroup/Meteor-Files/blob/master/LICENSE). I'll add licence to this rep too, thank you.

You're free to use any code from this repository, as long as original licence with copyright remains along to source code.

**Comment by elmarti** [comment]
Ok, thanks a lot!
