### ISSUE TITLE
V1 of Dropbox not supported anymore.

### ISSUE THREAD

**Issue by fillipefeitosa** [VeliovGroup/Meteor-Files-Demos#14]
=> Meteor server restarted                    
W20190326-17:30:35.105(0)? (STDERR) Dropbox API error 400 from POST https://api-content.dropbox.com/1/files_put/auto/RCNxAhyAr5Fpv5rwP-original.xlsx :: {"error": "v1_retired"} { triesSend: 10 }

This is the error I got using your demo app. Is there an update on the roadmap?

Thanks for your time.

**Comment by dr-dimitru** [comment]
Hello @fillipefeitosa ,

This is community driven package, and its docs as well, please feel free to contribute to our docs — https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/dropbox-integration.md
