### ISSUE TITLE
Delete files automatically after uploading

### ISSUE THREAD

**Issue by banana618859** [VeliovGroup/Meteor-Files-Demos#16]
### I'm having an issue:
  - Give an expressive description of what is went wrong
   Delete files automatically after uploading

  - Version of `Meteor-Files` you're experiencing this issue
    ostrio:files@1.11.0
  - Version of `Meteor` you're experiencing this issue
     METEOR@1.7.0.3
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
     Win 10
  - Is it *Client* or *Server* issue?
    Server  issue
  - Server side console
```
I20191010-20:07:54.367(8)? [FilesCollection] [_preCollectionCursor.observe] [changed]: h5LxFr7jnWqkKqSFQ
I20191010-20:07:54.370(8)? [FilesCollection] [_preCollectionCursor.observe] [removed]: h5LxFr7jnWqkKqSFQ
```

**Comment by dr-dimitru** [comment]
Hello @banana618859 ,

Please refer to [this thread](https://github.com/VeliovGroup/Meteor-Files/issues/250#issuecomment-251300402).

The logs you've posted are unrelated, this is just DEBUG information that intermediate collection (*starts with `_pre*`*) has fully sent data to the main collection and removed all pending records.

Feel free to reopen it in case if the issue is still persists on your end.

**Comment by banana618859** [comment]
@dr-dimitru [#250](https://github.com/VeliovGroup/Meteor-Files/issues/250)  thank your suggesstions,my problem be resolved,it is very good and happy.
when i upload my images,the images can be download.
but,then i stop meteor by [ctrl +c] twice
then , i run meteor again , type: meteor
the images can not be download
**by your suggestions, it worked.i just do this**
```
const Images = new FilesCollection({
  debug: true,
  collectionName: 'Images',
  storagePath: '/myupload/', // add the absolute path for images
  allowClientCode: false, // Disallow remove files from Client
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 1024 * 1024 * 10 && /png|jpe?g/i.test(file.extension)) {
      return true;
    }
    return 'Please upload image, with size equal or less than 10MB';
  }
});
```
thank you very much！

**Comment by dr-dimitru** [comment]
@banana618859 glad it's solved 🥳🎉

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - Donate via [Patreon](https://patreon.com/dr_dimitru) or [PayPal](https://paypal.me/veliovgroup)
