### ISSUE TITLE
Is there a demo using the latest /imports structure?

### ISSUE THREAD

**Issue by rlhk** [VeliovGroup/Meteor-Files-Demos#2]
The traditional way of putting Images in global scope is fine. However I can't get it to work by following the way other standard mongo collections are setup using the /imports structure. The 'images' collection doesn't show up in browser console: Meteor.Collection.getAll()

What are the possible differences ? Thanks.

**Comment by dr-dimitru** [comment]
Hello @rlhk 

From the [docs](https://github.com/VeliovGroup/Meteor-Files#es6-import):
```jsx
import { FilesCollection } from 'meteor/ostrio:files';
```

Yes, `FilesCollection !== Mongo.Collection`, how to use collection directly [read here](https://github.com/VeliovGroup/Meteor-Files/wiki/collection)

Is this helpful?

**Comment by rlhk** [comment]
Thanks for the hint.

Turns out it's not required to use collection directly. I just need to import once the `const Images = new FilesCollection ...` somewhere in the client code. Then the 'images' collection appears in `Meteor.Collection.getAll()`.  And publish becomes effective this way.

While I somehow imported all other collection defs in client. Maybe I just need to re-read the Meteor guide to understand more :)

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
