### ISSUE TITLE
Download Demo Doesn't Work

### ISSUE THREAD

**Issue by bnesbit** [VeliovGroup/Meteor-Files-Demos#3]
I can't get two of the MeteorFiles demos to work, I'll create an issue for each demo, this one is for the download demo. My setup steps included:

1. meteor create --bare meteor-files-demo-download-button
2. cd meteor-files-demo-download-button/
3. meteor npm install
4. meteor add ostrio:files
5. cp  demo-simplest-download-button/* . (downloaded via git first to a local directory)
6. meteor

This results in the error "Cannot find module '../core-js/symbol/iterator'". 

I tried to troubleshoot, including adding the xolio:core-js package, but my limited expertise & knowledge has left me unable to determine what I need to do to get the demo working. I don't know if I'm doing something wrong, or if the demo is broken. If there are dependencies, it would be good if they were documented.

**Comment by dr-dimitru** [comment]
Not sure what happens to meteor when you copy files from existing project to new one, and plain `cp` command skips files which starts with `.` (hidden files).

Just clone or download this repository to your working station and run `meteor update`, `meteor npm install` and then `meteor` to run the project.

**Comment by haibo32012** [comment]
haibo@haibo-251:~/github/demo$ meteor npm install

> Meteor-Files@1.7.13 preinstall /home/haibo/github/demo
> cd ./programs/server && npm install

sh: 1: cd: can't cd to ./programs/server

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/home/haibo/.meteor/packages/meteor-tool/.1.4.3_2.13aht4s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/haibo/.meteor/packages/meteor-tool/.1.4.3_2.13aht4s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install"
npm ERR! node v4.8.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! Meteor-Files@1.7.13 preinstall: `cd ./programs/server && npm install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the Meteor-Files@1.7.13 preinstall script 'cd ./programs/server && npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Meteor-Files package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./programs/server && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Meteor-Files
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Meteor-Files
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/haibo/.meteor/packages/meteor-tool/.1.4.3_2.13aht4s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-03-16T13_46_36_232Z-debug.log

i also got a error when run  **meteor npm install**, i can't figure out what's going on.

**Comment by dr-dimitru** [comment]
```shell
meteor npm -v
# must return version >= 4.3.0
```

```shell
meteor node -v
# must return version >= 4.8.0
```

Quick guess - you have to run `meteor update`, looks like you're on older meteor version

**Comment by haibo32012** [comment]
haibo@haibo-251:~/github/demo$ **meteor update**
This project is already at Meteor 1.4.3.2, the latest release.
                                                                                
Changes to your project's package version selections from updating package
versions:
                                              
blaze                  upgraded from 2.3.0 to 2.3.1
blaze-html-templates   upgraded from 1.1.0 to 1.1.1
caching-html-compiler  upgraded from 1.1.0 to 1.1.1
markdown               upgraded from 1.0.11 to 1.0.12
spacebars              upgraded from 1.0.13 to 1.0.14
spacebars-compiler     upgraded from 1.1.0 to 1.1.1
templating             upgraded from 1.3.0 to 1.3.1
templating-compiler    upgraded from 1.3.0 to 1.3.1
templating-runtime     upgraded from 1.3.0 to 1.3.1
templating-tools       upgraded from 1.1.0 to 1.1.1

                                              
The following top-level dependencies were not updated to the very latest
version available:
 * fourseven:scss 3.13.0 (4.5.0 is available) 
haibo@haibo-251:~/github/demo$ **meteor npm install**

> Meteor-Files@1.7.13 preinstall /home/haibo/github/demo
> cd ./programs/server && npm install

sh: 1: cd: can't cd to ./programs/server

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/home/haibo/.meteor/packages/meteor-tool/.1.4.3_2.13aht4s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/haibo/.meteor/packages/meteor-tool/.1.4.3_2.13aht4s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install"
npm ERR! node v4.8.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! Meteor-Files@1.7.13 preinstall: `cd ./programs/server && npm install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the Meteor-Files@1.7.13 preinstall script 'cd ./programs/server && npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Meteor-Files package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./programs/server && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Meteor-Files
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Meteor-Files
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/haibo/.meteor/packages/meteor-tool/.1.4.3_2.13aht4s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-03-17T00_45_19_543Z-deb

seem not that problem, before i test this project, i have update meteor to the latest.

**Comment by dr-dimitru** [comment]
```shell
 #sh: 1: cd: can't cd to ./programs/server
```

Means project isn't build yet, build it with `meteor build ../`
Or run with `meteor` command

**Comment by haibo32012** [comment]
haibo@haibo-251:~/github/demo$ meteor
[[[[[ ~/github/demo ]]]]]                     

=> Started proxy.                             
=> Started MongoDB.                           
W20170317-10:14:47.167(8)? (STDERR) /home/haibo/github/demo/.meteor/local/build/programs/server/boot.js:356
W20170317-10:14:47.221(8)? (STDERR) }).run();
W20170317-10:14:47.221(8)? (STDERR)    ^
W20170317-10:14:47.221(8)? (STDERR) 
W20170317-10:14:47.222(8)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules 
W20170317-10:14:47.222(8)? (STDERR) directory. Please run the following command to install it:
W20170317-10:14:47.223(8)? (STDERR) 
W20170317-10:14:47.223(8)? (STDERR)   meteor npm install --save babel-runtime
W20170317-10:14:47.224(8)? (STDERR) 
W20170317-10:14:47.225(8)? (STDERR)     at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
W20170317-10:14:47.225(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170317-10:14:47.225(8)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170317-10:14:47.226(8)? (STDERR)     at packages/babel-runtime.js:139:15
W20170317-10:14:47.226(8)? (STDERR)     at packages/babel-runtime.js:150:3
W20170317-10:14:47.226(8)? (STDERR)     at /home/haibo/github/demo/.meteor/local/build/programs/server/boot.js:303:34
W20170317-10:14:47.226(8)? (STDERR)     at Array.forEach (native)
W20170317-10:14:47.227(8)? (STDERR)     at Function._.each._.forEach (/home/haibo/.meteor/packages/meteor-tool/.1.4.3_2.13aht4s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170317-10:14:47.227(8)? (STDERR)     at /home/haibo/github/demo/.meteor/local/build/programs/server/boot.js:128:5
W20170317-10:14:47.227(8)? (STDERR)     at /home/haibo/github/demo/.meteor/local/build/programs/server/boot.js:352:5
=> Exited with code: 1
W20170317-10:14:49.097(8)? (STDERR) /home/haibo/github/demo/.meteor/local/build/programs/server/boot.js:356
W20170317-10:14:49.098(8)? (STDERR) }).run();
W20170317-10:14:49.098(8)? (STDERR)    ^
W20170317-10:14:49.098(8)? (STDERR) 
W20170317-10:14:49.098(8)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules 
W20170317-10:14:49.098(8)? (STDERR) directory. Please run the following command to install it:
W20170317-10:14:49.099(8)? (STDERR) 
W20170317-10:14:49.099(8)? (STDERR)   meteor npm install --save babel-runtime
W20170317-10:14:49.099(8)? (STDERR) 
W20170317-10:14:49.099(8)? (STDERR)     at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
W20170317-10:14:49.099(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170317-10:14:49.099(8)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170317-10:14:49.100(8)? (STDERR)     at packages/babel-runtime.js:139:15
W20170317-10:14:49.101(8)? (STDERR)     at packages/babel-runtime.js:150:3
W20170317-10:14:49.102(8)? (STDERR)     at /home/haibo/github/demo/.meteor/local/build/programs/server/boot.js:303:34
W20170317-10:14:49.102(8)? (STDERR)     at Array.forEach (native)
W20170317-10:14:49.103(8)? (STDERR)     at Function._.each._.forEach (/home/haibo/.meteor/packages/meteor-tool/.1.4.3_2.13aht4s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170317-10:14:49.103(8)? (STDERR)     at /home/haibo/github/demo/.meteor/local/build/programs/server/boot.js:128:5
W20170317-10:14:49.104(8)? (STDERR)     at /home/haibo/github/demo/.meteor/local/build/programs/server/boot.js:352:5
=> Exited with code: 1
W20170317-10:14:50.571(8)? (STDERR) /home/haibo/github/demo/.meteor/local/build/programs/server/boot.js:356
W20170317-10:14:50.572(8)? (STDERR) }).run();
W20170317-10:14:50.572(8)? (STDERR)    ^
W20170317-10:14:50.573(8)? (STDERR) 
W20170317-10:14:50.574(8)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules 
W20170317-10:14:50.574(8)? (STDERR) directory. Please run the following command to install it:
W20170317-10:14:50.574(8)? (STDERR) 
W20170317-10:14:50.574(8)? (STDERR)   meteor npm install --save babel-runtime
W20170317-10:14:50.575(8)? (STDERR) 
W20170317-10:14:50.575(8)? (STDERR)     at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
W20170317-10:14:50.575(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170317-10:14:50.576(8)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170317-10:14:50.576(8)? (STDERR)     at packages/babel-runtime.js:139:15
W20170317-10:14:50.576(8)? (STDERR)     at packages/babel-runtime.js:150:3
W20170317-10:14:50.576(8)? (STDERR)     at /home/haibo/github/demo/.meteor/local/build/programs/server/boot.js:303:34
W20170317-10:14:50.576(8)? (STDERR)     at Array.forEach (native)
W20170317-10:14:50.576(8)? (STDERR)     at Function._.each._.forEach (/home/haibo/.meteor/packages/meteor-tool/.1.4.3_2.13aht4s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170317-10:14:50.577(8)? (STDERR)     at /home/haibo/github/demo/.meteor/local/build/programs/server/boot.js:128:5
W20170317-10:14:50.577(8)? (STDERR)     at /home/haibo/github/demo/.meteor/local/build/programs/server/boot.js:352:5
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by dr-dimitru** [comment]
```shell
meteor npm install
meteor
```

**Comment by haibo32012** [comment]
yes, i have run meteor npm install. i am ready read some code and see if i can figure out, thanks for your answer.

**Comment by haibo32012** [comment]
@dr-dimitru Could you tell me why the code can write like this:
```
h1.percentage #{status.progress}%
      progress(max="100" value="#{status.progress}")
      p
        | #{status.estimateDuration}
        | &nbsp;
        | &middot;
        | &nbsp;
        | #{status.estimateBitrate}
      p
```
`#{status.progress}` what's this mean? I never see this before and do not see example like this in Spacebars document, thank you!

**Comment by dr-dimitru** [comment]
@haibo32012 ,

The `#{}` structure is JADE syntax for `{{}}` in Spacebars.
See the [docs](https://github.com/mquandalle/meteor-jade#templates)

**Comment by haibo32012** [comment]
@dr-dimitru , Thanks for your help, I finished the upload function.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
