### ISSUE TITLE
Please provide demo source in Blaze/Mustache

### ISSUE THREAD

**Issue by Sojourneer** [VeliovGroup/Meteor-Files-Demos#5]
I would like to use your package, but I cannot make any sense  of the Jade source code.
Thank you.

**Comment by dr-dimitru** [comment]
- [demo-simplest-upload](https://github.com/VeliovGroup/Meteor-Files-Demos/tree/master/demo-simplest-upload/client)
 - [demo-simplest-streaming](https://github.com/VeliovGroup/Meteor-Files-Demos/tree/master/demo-simplest-streaming/client)
 - [demo-simplest-download-button](https://github.com/VeliovGroup/Meteor-Files-Demos/tree/master/demo-simplest-download-button/client)

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
