### ISSUE TITLE
How to make preview? After switching off from AutoForm

### ISSUE THREAD

**Issue by ApayRus** [VeliovGroup/Meteor-Files-Demos#7]
I used code from demo-simplest-upload and I don't know how to handle showing preview of file. Please, could you explain it for me ? 

First I was using AutoForm , and there always with image be ok:

![peek 2017-10-14 20-28](https://user-images.githubusercontent.com/1222611/31578092-fee8b514-b122-11e7-926a-9fbd47f98a62.gif)

And it means, than biggest part of code are working fine. I just need a part , that was included to "AutoForm files" . 

I rewrited my code without AutoForm, and took a code from this demo, but I can't figure out how to rich the same functionality. How it looks now (why information about uploaded file is missing? ) : 

![peek 2017-10-14 20-32](https://user-images.githubusercontent.com/1222611/31578136-ab00d6ec-b123-11e7-8e5b-34aae706ef40.gif)

**Comment by dr-dimitru** [comment]
Hello @Aparus ,

Take [upload result `fileObj`](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo-simplest-upload/client/main.js#L39) and pass it into [`fileURL`](https://github.com/VeliovGroup/Meteor-Files/wiki/Template-Helper)

Easiest is to use *Session* or *ReactiveVar* to store upload result, and return via Template's helper. Then in a template:
```js
Template.uploadForm.onCreated(function () {
  this.currentUpload = new ReactiveVar(false);
  this.uploadedFile = new ReactiveVar(false);
});

Template.uploadForm.helpers({
  currentUpload: function () {
    return Template.instance().currentUpload.get();
  },
  uploadedFile: function () {
    return Template.instance().uploadedFile.get();
  }
});

Template.uploadForm.events({
  'change #fileInput': function (e, template) {
        /*...*/
        uploadInstance.on('end', function(error, fileObj) {
          if (error) {
            window.alert('Error during upload: ' + error.reason);
          } else {
            template.uploadedFile.set(fileObj);
            window.alert('File "' + fileObj.name + '" successfully uploaded');
          }
          template.currentUpload.set(false);
        });
       /*...*/
    }
  }
});
```
```html
<img src="{{fileURL uploadedFile}}" />
```

**Comment by ApayRus** [comment]
Thanks for quick answer! 
Now I can't connect image from uploadForm and parrent template data ( 
I use uploadForm inside ArticleForm. And when I add or remove image with old Autoform, image appears or disappears from article. But in template.data.pucture field always have some fixed image Id...
It's so strange.

**Comment by dr-dimitru** [comment]
@Aparus show more of your code. And if you need to exchange data between different templates use [Sessions](http://docs.meteor.com/api/session.html)

**Comment by ApayRus** [comment]
Thank you very much! I don't won't to bother you, I will try it myself, if I can't understand, then I'll reopen this issue ok?

**Comment by dr-dimitru** [comment]
@Aparus sure. Keep it up.

**Comment by Aparus** [comment]
I did it with Sessions. Now, what about removing? It is enough to just remove image from collection Images? (I use S3 integration) Or it only clear information about image in db, but file steel exist on the server?
